language: ruby
rvm:
  - "2.0.0"
  - "2.1.0-preview2"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
      - "justin@curationexperts.com"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
